apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    system: {{ .Values.system }}
    component: {{ .Values.component }}
  name: {{ .Values.component }}
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ .Values.component }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect