---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: {{ .Values.component }}-el
spec:
  serviceAccountName: pipeline
  triggers:
    - name: dev-trigger
      bindings:
        - kind: ClusterTriggerBinding
          ref: github-push
      interceptors:
        - params:
            - name: git-revision
              value: >-
                (body.ref.contains('{{ .Values.git.branch }}') || body.ref.contains('staging'))
            - name: overlays
              value: null
          ref:
            name: cel
      template:
        ref: {{ .Values.component }}-run-pipeline
    - name: qa-trigger
      bindings:
        - kind: ClusterTriggerBinding
          ref: github-pullreq
      interceptors:
        - params:
            - name: pullreq-title
              value: >-
                body.pull_request.title.contains('staging')
            - name: pullreq-action
              value: >-
                (body.action in ['closed'] && body.pull_request.merged == true)
            - name: overlays
              value: null
          ref:
            name: cel
      template:
        ref: { { .Values.component } }-run-pipeline


