---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: {{ .Values.component }}-el
spec:
  serviceAccountName: pipeline
  triggers:
    - name: dev-trigger
      bindings:
        - name: git-revision
          value: $(extensions.ref)
      interceptors:
        - params:
            - name: "filter"
              value: >-
                body.ref.contains('main')
            - name: overlays
              value:
                - key: git-revision
                  expression: "body.ref.split('/')[2]"
          ref:
            name: cel
      template:
        ref: "{{ .Values.component }}-run-pipeline"
    - name: qa-trigger
      bindings:
        - name: git-revision
          value: $(extensions.ref)
      interceptors:
        - params:
            - name: "filter"
              value: >-
                (header.match('X-GitHub-Event', 'pull_request') && (body.pull_request.title.contains('staging') || body.pull_request.title.contains('production')) && body.action in ['closed'] && body.pull_request.merged == true)
            - name: overlays
              value:
                - key: git-revision
                  expression: "body.ref.split('/')[2]"
          ref:
            name: cel
      template:
        ref: "{{ .Values.component }}-run-pipeline"



