---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: {{ .Values.component }}-el
spec:
  serviceAccountName: pipeline
  triggers:
    - name: dev-trigger
      bindings:
        - kind: ClusterTriggerBinding
          ref: github-push
      interceptors:
        - params:
            - name: "filter"
              value: >-
                body.ref.contains('main') && !(commits[0].message.contains("code-analysis"))
            - name: overlays
              value:
                - key: git-revision
                  expression: "body.ref.split('/')[2]"
          ref:
            name: cel
      template:
        ref: "{{ .Values.component }}-run-pipeline"
    - name: qa-trigger
      bindings:
          - kind: ClusterTriggerBinding
            ref: github-pullreq
      interceptors:
        - params:
            - name: "filter"
              value: >-
                (header.match('X-GitHub-Event', 'pull_request') && (pull_request.base.ref.contains('staging') || pull_request.base.ref.contains('production')) && body.action in ['closed'] && body.pull_request.merged == true)
            - name: overlays
              value:
                - key: git-revision
                  expression: pull_request.base.ref.split('/')[2]"
          ref:
            name: cel
      template:
        ref: "{{ .Values.component }}-run-pipeline"



