---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: {{ .Values.component }}-el
spec:
  serviceAccountName: pipeline
  triggers:
    - name: dev-trigger
      bindings:
        - kind: ClusterTriggerBinding
          name: git-revision
          value: $(expressions.git-revision)
      interceptors:
        - params:
            - name: "filter"
              value: >-
                body.ref.contains('main') && !(commits[0].message.contains("code-analysis"))
            - name: overlays
              value:
                - key: git-revision
                  expression: "body.ref.split('/')[2]"
          ref:
            name: cel
      template:
        ref: "{{ .Values.component }}-run-pipeline"
    - name: qa-trigger
      bindings:
        - kind: ClusterTriggerBinding
          name: git-revision
          value: $(expressions.git-revision)
      interceptors:
        - params:
            - name: "filter"
              value: >-
                body.action=='closed'
            - name: overlays
              value:
                - key: git-revision
                  expression: "body.pull_request.base.ref.split('/')[2]"
          ref:
            name: cel
      template:
        ref: "{{ .Values.component }}-run-pipeline"



