kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: get-deployment
  namespace: {{ $.Values.system }}-build
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: smongiar-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin