apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .Values.component }}-service
  labels:
    system: {{ .Values.system }}
spec:
  workspaces:
  - name: maven-repo
  - name: maven-settings

  params:
    - default: https://github.com/{{ .Values.domain }}/{{ .Values.system }}-{{ .Values.component }}-service
      name: git-url
      type: string
      description: "component source Git pepository"
    - default: main
      name: git-revision
      type: string
      description: "component source Git revision"
    - default: refs/heads/main
      name: app-source-branch
      type: string
      description: "source branch for code quality"
    - default: ./src/main/docker/Dockerfile
      name: dockerfilePath
      type: string
      description: "path to Dockerfile"
    - default: {{ .Values.image.registry }}/{{ .Values.system }}-build/{{ .Values.component }}
      name: image
      type: string
      description: "container image"
    - default: latest
      name: version
      type: string
      description: "release version"

  tasks:
  - name: clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.git-revision)
      - name: subdirectory
        value: "app"
      - name: verbose
        value: "true"
    workspaces:
    - name: output
      workspace: maven-repo

  - name: build
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter: ["clone"]
    params:
      - name: CONTEXT_DIR
        value: "app"
      - name: GOALS
        value:
          - compile
          - '-B'
    workspaces:
    - name: source
      workspace: maven-repo
    - name: maven-settings
      workspace: maven-settings

  - name: code-analysis
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
      - package
    workspaces:
      - name: source
        workspace: maven-repo
      - name: maven-settings
        workspace: maven-settings
    params:
      - name: GOALS
        value:
          - install
          - sonar:sonar
          - -Dsonar.host.url=http://sonarqube-sonarqube.sonarqube.svc.cluster.local:9000
          - -Dsonar.userHome=/tmp/sonar
          - -DskipTests=true

  - name: package
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter: ["build"]
    params:
    - name: CONTEXT_DIR
      value: "app"
    - name: GOALS
      value: 
        - package
        - -DskipTests
        - '-B'
    workspaces:
    - name: source
      workspace: maven-repo
    - name: maven-settings
      workspace: maven-settings

  - name: code-analysis
    taskRef:
      name: maven
      kind: ClusterTask
    when:
      - input: $(params.git-revision)
        operator: in
        values:
          - "main"
    runAfter:
      - package
    workspaces:
      - name: source
        workspace: maven-repo
      - name: maven-settings
        workspace: maven-settings
    params:
      - name: CONTEXT_DIR
        value: "app"
      - name: GOALS
        value:
          - install
          - sonar:sonar
          - -Dsonar.host.url=http://sonarqube-sonarqube.sonarqube.svc.cluster.local:9000
          - -Dsonar.userHome=/tmp/sonar
          - -DskipTests=true

  - name: cve-scan-local-image
    taskRef:
      name: trivy-scanner
      kind: Task
    when:
      - input: $(params.git-revision)
        operator: in
        values:
          - "staging"
    params:
      - name: ARGS
        value:
          - "image"
          - "--light"
          - "--exit-code"
          - "1"
          - "--severity"
          - "CRITICAL"
      - name: IMAGE_PATH
        value: $(params.image):$(params.version)
    workspaces:
      - name: manifest-dir
        workspace: maven-repo
    runAfter:
      - package

  - name: promote-pr
    runAfter:
      - code-analysis
      - cve-scan-local-image
    taskRef:
      name: create-promote-pull-request
    when:
      - input: $(params.git-revision)
        operator: notin
        values:
          - "production"
    params:
      - name: GIT_BRANCH
        value: $(params.git-revision)
      - name: OWNER
        value: {{ .Values.system }}
    workspaces:
      - name: output
        workspace: maven-repo

  - name: build-container-image
    runAfter: ["package"]
    taskRef:
      name: buildah
      kind: ClusterTask
    workspaces:
    - name: source
      workspace: maven-repo
    params:
    - name: IMAGE
      value: $(params.image):$(params.version)
    - name: CONTEXT
      value: "app"
    - name: DOCKERFILE
      value: $(params.dockerfilePath)

  - name: deploy-to-dev
    runAfter: 
      - build-container-image 
    taskRef:
      name: openshift-client
      kind: ClusterTask
    when:
      - input: $(params.git-revision)
        operator: in
        values:
          - "main"
    params:
    - name: SCRIPT
      value: |
        set -x
        oc adm policy add-role-to-user cluster-admin system:serviceaccount:{{ .Values.system }}-build:pipeline 
        oc policy add-role-to-user system:image-puller system:serviceaccount:{{ .Values.system }}-dev:default --namespace={{ .Values.system }}-build
        oc rollout restart deployment/{{ .Values.component }} -n {{ .Values.system }}-dev

  - name: deploy-to-qa
    runAfter:
      - build-container-image
    taskRef:
      name: openshift-client
      kind: ClusterTask
    when:
      - input: $(params.git-revision)
        operator: in
        values:
          - "staging"
    params:
      - name: SCRIPT
        value: |
          set -x
          oc adm policy add-role-to-user cluster-admin system:serviceaccount:{{ .Values.system }}-build:pipeline 
          oc policy add-role-to-user system:image-puller system:serviceaccount:{{ .Values.system }}-qa:default --namespace={{ .Values.system }}-build
          oc rollout restart deployment/{{ .Values.component }} -n {{ .Values.system }}-qa

  - name: deploy-to-prod
    runAfter:
      - build-container-image
    taskRef:
      name: openshift-client
      kind: ClusterTask
    when:
      - input: $(params.git-revision)
        operator: in
        values:
          - "production"
    params:
      - name: SCRIPT
        value: |
          set -x
          oc adm policy add-role-to-user cluster-admin system:serviceaccount:{{ .Values.system }}-build:pipeline 
          oc policy add-role-to-user system:image-puller system:serviceaccount:{{ .Values.system }}-prod:default --namespace={{ .Values.system }}-build
          oc rollout restart deployment/{{ .Values.component }} -n {{ .Values.system }}-prod        


