apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.component }}-maven-settings
data:
  settings.xml: |
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
      <localRepository>/workspace/source/.m2</localRepository>
    </settings>