apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.component }}-pipeline-run-job
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  selector: {}
  template:
    metadata:
      name: {{ .Values.component }}-pipeline-run-job
    spec:
      containers:
          - name: {{ .Values.component }}-pipeline-run-job
            image: gcr.io/tekton-releases/dogfooding/tkn
            command:
              - /bin/sh
              - -c
              - |
                tkn pipeline start {{ .Values.component }}-service -w name=maven-repo,claimName={{ .Values.component }}-maven-repo -w name=maven-settings,claimName={{ .Values.component }}-maven-settings --use-param-defaults
            env:
              - name: HOME
                value: /tekton/home
      restartPolicy: Never
      serviceAccountName: pipeline