apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.component }}-pipeline-run-job
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  selector: {}
  template:
    metadata:
      name: {{ .Values.component }}-pipeline-run-job
    spec:
      containers:
          - name: {{ .Values.component }}-pipeline-run-job
            image: public.ecr.aws/logistics/tekton-releases/dogfooding/tkn:v.sha256.8d4383ff675cdf42b0006fca9b5b3b0c1d6180ff0013805242c877352e03a359
            command:
              - /bin/sh
              - -c
              - |
                tkn pipeline start {{ .Values.component }}-service -w name=maven-repo,claimName={{ .Values.component }}-workspace -w name=maven-settings,config={{ .Values.component }}-maven-settings --use-param-defaults
            env:
              - name: HOME
                value: /tekton/home
      restartPolicy: Never
      serviceAccountName: pipeline