---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.component }}-mvn-repo
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.component }}-mvn-settings
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
