---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-resources-role
  namespace: {{ .Values.system }}-build
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-creation-rolebinding
  namespace: {{ .Values.system }}-build
subjects:
  - kind: ServiceAccount
    name: pipeline
    apiGroups: ["*"]
    namespace: {{ .Values.system }}-build
roleRef:
  kind: Role
  name: pipeline-resources-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: {{ .Values.system }}-build








