---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader-role
  namespace: developer-hub
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["rhdh-secrets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-create-role
  namespace: {{ .Values.system }}-build
rules:
  - apiGroups: [""]
    resources: ["secret"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-rolebinding
  namespace: developer-hub
subjects:
  - kind: ServiceAccount
    name: pipeline
    apiGroups: [""]
    namespace: {{ .Values.system }}-build
roleRef:
  kind: Role
  name: secret-reader-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-creation-rolebinding
  namespace: {{ .Values.system }}-build
subjects:
  - kind: ServiceAccount
    name: pipeline
    apiGroups: [""]
    namespace: {{ .Values.system }}-build
roleRef:
  kind: Role
  name: secret-create-role
  apiGroup: rbac.authorization.k8s.io









