apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: git
  name: create-promote-pull-request
  labels:
    app.kubernetes.io/version: '0.1'
    operator.tekton.dev/provider-type: community
spec:
  description: This Task can be used to update image digest in a Git repo using the kustomize
  params:
    - name: GIT_REPOSITORY
      type: string
    - name: COPY_FROM
      type: string
    - name: COPY_TO
      type: string
  workspaces:
    - description: The workspace consisting of maven project.
      name: workspace
  results:
    - name: branch_name
      description: The branch name used for pull-request
  steps:
    - name: promote
      image: docker.io/alpine/git:v2.26.2
      workingDir: $(workspaces.workspace.path)
      script: |
        set -x
        rm -rf pull-request-workdir
        git clone $(params.GIT_REPOSITORY) pull-request-workdir
        cd pull-request-workdir

        branch_name=promoting-$(context.taskRun.name)-to-$(params.COPY_TO)-$(context.taskRun.uid)
        git checkout -b $branch_name
        echo -n "$branch_name" > $(results.branch_name.path)

        #/bin/cp -rf $(params.COPY_FROM_PATH)/* $(params.COPY_TO_PATH)

        git status
        git add $(params.COPY_TO_PATH)
        git commit -m "[$(context.taskRun.name)] Promotion from $(params.COPY_FROM_PATH) to $(params.COPY_TO_PATH)"

        git remote add auth-origin $(echo $(params.GIT_REPOSITORY))
        git push -u auth-origin HEAD