apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: git
  name: create-promote-pull-request
  labels:
    app.kubernetes.io/version: '0.1'
    operator.tekton.dev/provider-type: community
spec:
  description: This Task can be used to update image digest in a Git repo using the kustomize
  params:
    - name: GIT_BRANCH
      type: string
  workspaces:
    - description: The workspace consisting of maven project.
      name: source
  results:
    - name: target_branch_name
      description: The branch name used for pull-request
  steps:
    - name: promote
      image: mirror.gcr.io/alpine/git:v2.26.2
      workingDir: $(workspaces.source.path)
      script: |
        set -x
        rm -rf pull-request-workdir
        export sonarlink=$(awk 'match($0,/ceTaskUrl=[\s\S]*.+/){print substr($0,RSTART+10,RLENGTH-10)}' target/sonar/report-task.txt)
        wget $sonarlink
        mv task* sonar-result.txt
        export result=$(awk 'match($0,/"status":"[A-Z]+/){print substr($0,RSTART+10,RLENGTH-10)}' sonar-result.txt)
        
        while [ "$result" == "IN_PROGRESS" ]; do
          sleep 60
          export sonarlink=$(awk 'match($0,/ceTaskUrl=[\s\S]*.+/){print substr($0,RSTART+10,RLENGTH-10)}' target/sonar/report-task.txt)
          wget $sonarlink
          mv task* sonar-result.txt
          export result=$(awk 'match($0,/"status":"[A-Z]+/){print substr($0,RSTART+10,RLENGTH-10)}' sonar-result.txt)
        done
        
        if [ "$result" != "SUCCESS" ]; then
          echo "Quality Gate not passed"
          exit 1
        else 
          current_branch=$(echo $(params.GIT_BRANCH) | awk -F/ '{print $NF}')
          git checkout $current_branch
          echo -n "$current_branch" > $(results.source_branch_name.path)
        
          if [ "$current_branch" == "main" ]; then
            target_branch_name=staging
          elif [  "$current_branch" == "staging" ]; then
            target_branch_name=production
          fi
 
          echo -n "$target_branch_name" > $(results.target_branch_name.path)
        fi