---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: {{ .Values.component }}-run-pipeline
spec:
  params:
    - name: git-revision
      description: The git revision
      default: main	
    - name: git-url
      description: The repo url
      default: https://github.com/{{ .Values.domain }}/{{ .Values.system }}-{{ .Values.component }}-service 
    - name: image
      description: reference of the image that will get created
      default: {{ .Values.image.registry }}/{{ .Values.system }}-dev/{{ .Values.component }}
    - name: version
      description: tag of the image that will get created
      default: latest
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: {{ .Values.component }}-triggered
        labels:
          backstage.io/kubernetes-id: {{ .Values.component }}
      spec:
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: image
            value: $(tt.params.image)
          - name: version
            value: $(tt.params.version)
        pipelineRef:
          name: {{ .Values.component }}-service
        workspaces:
          - name: maven-repo
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: maven-settings
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi

