apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .Values.component }}-api
spec:
  description: | 
    This pipeline runs a Spectral linter against an API specification and publishes to Microcks and Apicurio Registry
  params:
  - default: https://github.com/{{ .Values.domain }}/{{ .Values.system }}-{{ .Values.component }}-api
    name: repo-url
    type: string
  - default: main
    name: git-revision
    type: string
  - default: "mirror.gcr.io/stoplight/spectral:6.11.1"
    name: spectral-image
    type: string
  - default: https://raw.githubusercontent.com/{{ .Values.domain }}/spectral-rules/main/ruleset.yaml
    name: rules-path
    type: string
  - default: ./specification.yaml
    name: api-path
    type: string
  workspaces:
  - name: shared-data
  - name: maven-settings
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: "$(params.git-revision)"
    workspaces:
    - name: output
      workspace: shared-data
  - name: run-spectral
    runAfter: ["fetch-source"]
    taskRef:
      name: spectral-quality-gate
      kind: ClusterTask
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: RULES_PATH
      value: $(params.rules-path)
    - name: API_PATH
      value: $(params.api-path)
    - name: IMAGE
      value: $(params.spectral-image)
  - name: run-microcks-import
    runAfter: ["run-spectral"]
    taskRef:
      name: microcks-import
      kind: ClusterTask
    workspaces:
    - name: data
      workspace: shared-data
  - name: register-apicurio
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter: ["run-spectral"]
    params:
    - name: GOALS
      value: 
        - generate-sources
    workspaces:
      - name: source
        workspace: shared-data
      - name: maven-settings
        workspace: maven-settings
