apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.component }}-api-pipeline-run-job
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  selector: {}
  template:
    metadata:
      name: {{ .Values.component }}-api-pipeline-run-job
    spec:
      containers:
          - name: {{ .Values.component }}-api-pipeline-run-job
            image: gcr.io/tekton-releases/dogfooding/tkn
            command:
              - /bin/sh
              - -c
              - |
                curl -X DELETE --silent http://{{ .Values.service_registry_provider_url }}/apis/registry/v2/groups/{{ .Values.groupid }}t/artifacts/{{ .Values.component }} && tkn pipeline start {{ .Values.component }}-api -w name=shared-data,claimName={{ .Values.component }}-shared-data -w name=maven-settings,claimName={{ .Values.component }}-maven-settings --use-param-defaults
            env:
              - name: HOME
                value: /tekton/home
      restartPolicy: Never
      serviceAccountName: pipeline