---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: {{ .Values.component }}-api-run-pipeline
spec:
  params:
    - name: git-revision
      description: The git revision
      default: main
    - name: repo-url
      description: The repo url
      default: https://github.com/smongiar/{{ .Values.system }}-{{ .Values.component }}-api
    - name: spectral-image
      description: reference of the spectral image
      default: "stoplight/spectral:6.11.1"
    - name: rules-path
      description: reference of ruleset.yaml
      default: https://raw.githubusercontent.com/smongiar/spectral-rules/main/ruleset.yaml
    - name: api-path
      description: reference of specification.yaml
      default: ./specification.yaml
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: {{ .Values.component }}-api-triggered
        labels:
          backstage.io/kubernetes-id: {{ .Values.component }}-api
      spec:
        params:
          - name: repo-url
            value: $(tt.params.repo-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: spectral-image
            value: $(tt.params.spectral-image)
          - name: rules-path
            value: $(tt.params.rules-path)
          - name: api-path
            value: $(tt.params.api-path)
        pipelineRef:
          name: {{ .Values.component }}-api
        serviceAccountName: pipeline
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: maven-settings
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi




