---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: {{ .Values.component }}-api-run-pipeline
spec:
  params:
    - name: git-revision
      description: The git revision
    - name: repo-url
      description: The repo url
    - name: spectral-image
      description: reference of the spectral image
    - name: rules-path
      description: reference of ruleset.yaml
    - name: api-path
      description: reference of specification.yaml
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: {{ .Values.component }}-api-triggered
        labels:
          backstage.io/kubernetes-id: {{ .Values.component }}-api
      spec:
        params:
          - name: repo-url
            value: $(tt.params.repo-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: spectral-image
            value: $(tt.params.spectral-image)
          - name: rules-path
            value: $(tt.params.rules-path)
          - name: api-path
            value: $(tt.params.api-path)
        pipelineRef:
          name: {{ .Values.component }}-api
        workspaces:
          - name: shared-data
            persistentVolumeClaim: {{ .Values.component }}-shared-data
          - name: maven-settings
            persistentVolumeClaim: {{ .Values.component }}-maven-settings




